export const mixers = [
  { value: "apple_juice", label: "Apple Juice" },
  { value: "blueberry_juice", label: "Blueberry Juice" },
  { value: "lemon_juice", label: "Lemon Juice" },
  { value: "lime_juice", label: "Lime Juice" },
  { value: "orange_juice", label: "Orange Juice" },
  { value: "pineapple_juice", label: "Pineapple Juice" },
  { value: "cranberry_juice", label: "Cranberry Juice" },
  { value: "grapefruit_juice", label: "Grapefruit Juice" },
  { value: "tomato_juice", label: "Tomato Juice" },
  { value: "coconut_water", label: "Coconut Water" },
  { value: "water", label: "Water" },
  { value: "soda", label: "Soda" },
  { value: "club_soda", label: "Club Soda" },
  { value: "tonic_water", label: "Tonic Water" },
  { value: "ginger_beer", label: "Ginger Beer" },
  { value: "ginger_ale", label: "Ginger Ale" },
  { value: "cola", label: "Cola" },
  { value: "lemon_lime_soda", label: "Lemon-Lime Soda" },
  { value: "iced_tea", label: "Iced Tea" },
  { value: "energy_drink", label: "Energy Drink" },
  { value: "cream", label: "Cream" },
  { value: "milk", label: "Milk" },
  { value: "almond_milk", label: "Almond Milk" },
  { value: "coconut_milk", label: "Coconut Milk" },
  { value: "simple_syrup", label: "Simple Syrup" },
  { value: "grenadine", label: "Grenadine" },
];

// TODO: add special section for syrups in the future
export const syrups = [
  { value: "agave_syrup", label: "Agave Syrup" },
  { value: "maple_syrup", label: "Maple Syrup" },
  { value: "honey_syrup", label: "Honey Syrup" },
  { value: "orgeat", label: "Orgeat" },
  { value: "raspberry_syrup", label: "Raspberry Syrup" },
  { value: "vanilla_syrup", label: "Vanilla Syrup" },
  { value: "cinnamon_syrup", label: "Cinnamon Syrup" },
  { value: "ginger_syrup", label: "Ginger Syrup" },
  { value: "mint_syrup", label: "Mint Syrup" },
  { value: "lavender_syrup", label: "Lavender Syrup" },
  { value: "passion_fruit_syrup", label: "Passion Fruit Syrup" },
  { value: "elderflower_syrup", label: "Elderflower Syrup" },
  { value: "peach_syrup", label: "Peach Syrup" },
  { value: "hazelnut_syrup", label: "Hazelnut Syrup" },
  { value: "caramel_syrup", label: "Caramel Syrup" },
  { value: "gomme_syrup", label: "Gomme Syrup" },
];

// alcoholic - could be labeled or not
export const spirits = [
  { value: "gin", label: "Gin" },
  { value: "vodka", label: "Vodka" },
  { value: "rum", label: "Rum" },
  { value: "tequila", label: "Tequila" },
  { value: "bourbon", label: "Bourbon" },
  { value: "brandy", label: "Brandy" },
  { value: "sparkling wine", label: "Sparkling Wine" },
  { value: "champagne", label: "Champagne" },
  { value: "cognac", label: "Cognac" },
  { value: "whisky", label: "Whisky" },
  { value: "cachaca", label: "Cachaca" },

  // brands
  { value: "Bacardi", label: "Bacardi" },
  { value: "Beefeater", label: "Beefeater" },
  { value: "Ciroc", label: "Ciroc" },
  { value: "Crown Royal", label: "Crown Royal" },
  { value: "Glenfiddich", label: "Glenfiddich" },
  { value: "Havana Club", label: "Havana Club" },
  { value: "Jack Daniel's", label: "Jack Daniel's" },
  { value: "Jim Beam", label: "Jim Beam" },
  { value: "JW Red Label", label: "JW Red Label" },
  { value: "Tanqueray", label: "Tanqueray" },
  { value: "Bombay", label: "Bombay" },
  { value: "Martini", label: "Martini" },
  { value: "Nikka", label: "Nikka" },
  { value: "Absolut Blue", label: "Absolut Blue" },
  { value: "Absolut Raspberri", label: "Absolut Raspberri" },
  { value: "Absolut Mandrin", label: "Absolut Mandrin" },
  { value: "Absolut Mango", label: "Absolut Mango" },
  { value: "Absolut Pears", label: "Absolut Pears" },
  { value: "Pernod Ricard", label: "Pernod Ricard" },
];

export const moment = [
  { value: "pool_party", label: "Pool party" },
  { value: "birthday_party", label: "Birthday party" },
  { value: "wedding", label: "Wedding" },
  { value: "night_club", label: "Night club" },
  { value: "cocktail_bar", label: "Cocktail bar" },
  { value: "relaxing_at_home", label: "Relaxing at home" },
  { value: "at_the_beach", label: "At the beach" },
  { value: "dinner_party", label: "Dinner party" },
  { value: "brunch", label: "Brunch" },
  { value: "holiday_celebration", label: "Holiday celebration" },
  { value: "after_work", label: "After work" },
  { value: "date_night", label: "Date night" },
  { value: "game_night", label: "Game night" },
  { value: "barbecue", label: "Barbecue" },
  { value: "pre_dinner_aperitif", label: "Pre-dinner aperitif" },
  { value: "outdoor_festival", label: "Outdoor festival" },
  { value: "movie_night", label: "Movie night" },
  { value: "summer_picnic", label: "Summer picnic" },
  { value: "winter_gathering", label: "Winter gathering" },
  { value: "new_years_eve", label: "New Year's Eve" },
];

export const complexity = [
  { value: "easy", label: "Easy" },
  { value: "medium", label: "Medium" },
  { value: "hard", label: "Hard" },
];

export const tools = [
  { value: "glass", label: "Glass" },
  { value: "jigger", label: "Jigger" },
  { value: "muddler", label: "Muddler" },
  { value: "strainer", label: "Strainer" },
  { value: "twisted_spoon", label: "Twisted Spoon" },
  { value: "ice_filter", label: "Ice Filter" },
  { value: "bar_spoon", label: "Bar Spoon" },
  { value: "mixing_glass", label: "Mixing Glass" },
  { value: "ice_tongs", label: "Ice Tongs" },
  { value: "peeler", label: "Peeler" },
  { value: "citrus_juicer", label: "Citrus Juicer" },
  { value: "zester", label: "Zester" },
  { value: "cocktail_picks", label: "Cocktail Picks" },
  { value: "bottle_opener", label: "Bottle Opener" },
  { value: "corkscrew", label: "Corkscrew" },
  { value: "ice_crusher", label: "Ice Crusher" },
  { value: "fine_mesh_strainer", label: "Fine Mesh Strainer" },
  { value: "grater", label: "Grater" },
  { value: "garnish_knife", label: "Garnish Knife" },
];
